### ISSUE TITLE
Licencing issue

### ISSUE THREAD

**Issue by Spoonrad** [cykerway/jinja-cli#8]
Hi there,

I'm interested in using this library in our proprietary software, for commercial use. Unfortunately, your licence (GPLv3) is too legally insecure for commercial use.

Would you consider changing your licence to something more permissive, such as MIT?

Thanks in advance for your work & your feedback, we'd love to use jinja-cli in our projects!

**Comment by cykerway** [comment]
Hello, I have several practical reasons to keep using GPL as the current license. But before those matter, I am curious where GPL would become "legally insecure for commercial use". To the best of my knowledge, GPL doesn't prohibit commercial use as long as the commercial use is in accordance with the license. GPL does have an aversion to proprietary systems, but it still allows you to copy and run the program without distribution (convey). Since this is a command line tool, I didn't expect many users to distribute the tool itself. So would you please confirm your use case indeed requires distribution of this tool? Should the answer be "yes", I can give you more explanation and seek viable solution. Otherwise I believe the current license is already a fit for your need.

By the way, this and all further conversations are to the best of my knowledge and informational only, not legal advise. You are free to consult your own lawyer and correct me if I made a mistake.

**Comment by Spoonrad** [comment]
@cykerway  You are correct, I have a better understanding of GPL now and since your tool is a CLI tool, its usage does not result in a combined work. Thank you very much for your reply!
